### ISSUE TITLE
package.json error

### ISSUE THREAD

**Issue by izio38** [Bad57/ragP#1]
There is an error in your package.json

```json

{
    "author": "Bad",
    "version": "1.0",
    "server_scripts": [
        "server.lua",
        "settings.lua"
    ],
    "client_scripts": [
        "client.lua"
    ],
    "files": [
    ]
}
```
It should be this. For instance, the package isn't working without

**Comment by Bad57** [comment]
Bonjour,

J'ai corrigé l'erreur qui était présente dans le fichier.

Merci beaucoup :)
